services:
  postgres:
    image: postgres:15
    container_name: postgresql
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    build:
      context: ./aut-jwt
      dockerfile: Dockerfile
    image: aut_jwt_app:latest
    container_name: aut_jwt_app
    working_dir: /app
    ports:
      - "8081:8080"
    depends_on:
      - postgres