server:
    port: ${PORT:8080}
    servlet:
        context-path: /api
sptingdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui
spring:
  datasource:
    url: jdbc:postgresql://${HOST_NAME}:${PORT_NAME}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
  application:
    name: aut-jwt
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000
  issuer: aut-jwt-issuer
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info
